#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


if git diff --cached --name-only | grep -q "^tp6-mock-react/"; then
  echo "→ Running checks for TP2"
  cd ../tp6-mock-react || exit 1
  npm install # optional
  npm run lint
  npm test
fi
