name: CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tp6-mock-react
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installer les dépendances
        run: npm install
      - name: Lancer le linter
        run: npm run lint
      - name: Exécuter les tests Playwright
        run: npx playwright install --with-deps && npm run test
      - name: Enregistrer les résultats en cas d'échec
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/