name: CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Installer les dépendances
        run: npm i
      - name: Lancer le linter
        run: npm run lint
      - name: Exécuter les tests Playwright
        run: npm test
      - name: Enregistrer les résultats en cas d'échec
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/